export enum Configuration {
  APP_PORT = "APP_PORT",
  DB_CONNECTION = "DB_CONNECTION",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_DATABASE = "DB_DATABASE",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD"
}
